module.exports = {
  name: 'Localization',
  title: 'Localization of YNAB',
  default: '0',
  description: 'Localization of interface.',
  section: 'general',
  type: 'select',
  options: [
    { name: 'Default', value: '0' },
    { name: 'Arabic (27%)', value: 'arabic' },
    { name: 'Catalan (1%)', value: 'catalan' },
    { name: 'Chinese Simplified (14%)', value: 'chinese simplified' },
    { name: 'Chinese Traditional (39%)', value: 'chinese traditional' },
    { name: 'Czech (64%)', value: 'czech' },
    { name: 'Danish (48%)', value: 'danish' },
    { name: 'Dutch (46%)', value: 'dutch' },
    { name: 'Finnish (46%)', value: 'finnish' },
    { name: 'French (49%)', value: 'french' },
    { name: 'German (48%)', value: 'german' },
    { name: 'Hungarian (41%)', value: 'hungarian' },
    { name: 'Icelandic (5%)', value: 'icelandic' },
    { name: 'Indonesian (85%)', value: 'indonesian' },
    { name: 'Italian (15%)', value: 'italian' },
    { name: 'Korean (1%)', value: 'korean' },
    { name: 'Latvian (12%)', value: 'latvian' },
    { name: 'Lithuanian (1%)', value: 'lithuanian' },
    { name: 'Norwegian (48%)', value: 'norwegian' },
    { name: 'Polish (85%)', value: 'polish' },
    { name: 'Portuguese, Brazilian (56%)', value: 'portuguese, brazilian' },
    { name: 'Portuguese (21%)', value: 'portuguese' },
    { name: 'Romanian (2%)', value: 'romanian' },
    { name: 'Russian (48%)', value: 'russian' },
    { name: 'Slovenian (1%)', value: 'slovenian' },
    { name: 'Spanish (83%)', value: 'spanish' },
    { name: 'Swedish (49%)', value: 'swedish' },
    { name: 'Tagalog (1%)', value: 'tagalog' },
    { name: 'Turkish (85%)', value: 'turkish' },
    { name: 'Ukrainian (5%)', value: 'ukrainian' },
    { name: 'Vietnamese (12%)', value: 'vietnamese' }
  ]
};
